# Generated by Django 3.1.7 on 2021-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_afericao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afericao',
            options={'verbose_name_plural': 'Aferições'},
        ),
        migrations.AlterField(
            model_name='afericao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
