# Generated by Django 3.1.7 on 2021-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0011_auto_20210219_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afericao',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
