# Generated by Django 3.1.7 on 2021-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0015_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afericao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
